apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: mysql-container
          image: dusdjhyeon/mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: mydelivery
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
        - name: api-container
          image: dusdjhyeon/delivery:1.0
          env: 
            - name: MYSQL_HOST
              value: db
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: password
            - name: MYSQL_DATABASE
              value: mydelivery
          ports:
            - containerPort: 8000
      volumes:
        - name: db-data
          emptyDir: {}
        - name: init-sql
          configMap:
            name: init-sql-configmap
